### ISSUE TITLE
Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by klarstrup** [hello-pangea/dnd#450]
https://github.com/hello-pangea/dnd/blob/02daac951338d40127bc2e1b989b9116a989debc/src/view/droppable/connected-droppable.ts#L277

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1567633/211830847-94898c64-64b4-4300-82c1-8453a73f51a6.png">

**Comment by rubenprodev** [comment]
Getting same warning here. Any workaround or solution?

**Comment by klarstrup** [comment]
Yeah it is merging https://github.com/hello-pangea/dnd/pull/452

I also published https://www.npmjs.com/package/@klarstrup/dnd back when I made the PR, but I don't keep it updated.

**Comment by rubenprodev** [comment]
I see is not ready yet due to some misspassing tests. Thank you for your solution, but I actually don't want to use another package in its place. Maybe update the pull request in order to fix it?

**Comment by namnhfreelancer** [comment]
@klarstrup 
<img width="1299" alt="image" src="https://github.com/hello-pangea/dnd/assets/12831283/1d4975d2-f550-4bcd-b0ae-0c89a1c8a903">
I tried your npm package but still see warning. Any solution ?

**Comment by 100terres** [comment]
Thank you for bringing this to our attention :blush:

We made the required change in [this PR](https://github.com/hello-pangea/dnd/pull/579) and it will be part of the next release!
